# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DhruvKoolRajamani
email: dhruvkoolrajamani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My interests lie in the field of non-linear control and Robot dynamics. To cultivate my interest, I am researching on the control of a flexible manipulator using differential flatness. I am a robotics enthusiast and wish to pursue further studies to better develop my interests and understanding of robots.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
plugins:
  - jekyll-seo-tag
# Build settings
markdown: kramdown
#highlighter: pygments
permalink: /:title
